import { pathBasename } from "../utils/pathUtils";
import { branchKeyFor, resolveRepoPathFor } from "./repositories";
import { type BaseTab, createTabManager } from "./tabManager";

// Zoom bounds mirror the terminal zoom (useTerminalLifecycle) for consistency.
const MD_MIN_FONT_SIZE = 8;
const MD_MAX_FONT_SIZE = 32;
const MD_FONT_STEP = 2;
/** Default matches #markdown-content font-size: var(--font-lg) = 15px in styles.css */
export const MD_DEFAULT_FONT_SIZE = 15;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** File-based markdown tab (reads content from the filesystem via Tauri) */
export interface FileTab extends BaseTab {
	type: "file";
	repoPath: string;
	filePath: string;
	/** Display name (basename of filePath) */
	fileName: string;
	/** Effective filesystem root for I/O (worktree path when on a linked worktree, otherwise same as repoPath) */
	fsRoot?: string;
}

/** Virtual markdown tab (content generated by a plugin via markdownProviderRegistry) */
export interface VirtualTab extends BaseTab {
	type: "virtual";
	title: string;
	/** URI routed through markdownProviderRegistry, e.g. "plan:file?path=/foo.md" */
	contentUri: string;
}

/** Plugin panel tab (renders HTML in a sandboxed iframe via PluginPanel component) */
export interface PluginPanelTab extends BaseTab {
	type: "plugin-panel";
	title: string;
	/** The plugin that owns this panel */
	pluginId: string;
	/**
	 * The panel's identity within its plugin — `OpenPanelOptions.id`. Two
	 * openPanel calls with the same key are the same panel, whatever the title
	 * says; a dashboard that names itself after the active repo must not spawn a
	 * second tab. Absent on MCP `ui action=tab` panels, which key on pluginId.
	 */
	panelKey?: string;
	/** HTML content rendered inside the sandboxed iframe */
	html: string;
	/** Optional URL to load instead of inline HTML (mutually exclusive with html) */
	url?: string;
	/**
	 * Source-derived styling mode. Undefined/false for SDK plugin dashboards
	 * (`addPluginPanel`) — they get PLUGIN_BASE_CSS forced on so the shared
	 * `.dashboard`/`.dash-*` classes render. True for MCP `ui action=tab` design/
	 * preview tabs (`openUiTab`) — they keep their own background/typography and
	 * the base sheet is omitted (#080).
	 */
	selfStyled?: boolean;
}

/** Native Claude Usage Dashboard tab */
export interface ClaudeUsageTab extends BaseTab {
	type: "claude-usage";
	title: string;
}

/** Native GitHub Ops Dashboard tab (repo-scoped) */
export interface GithubOpsTab extends BaseTab {
	type: "github-ops";
	title: string;
	repoPath: string;
}

/** PR diff tab (renders a full PR diff in the main panel) */
export interface PrDiffTab extends BaseTab {
	type: "pr-diff";
	title: string;
	repoPath: string;
	prNumber: number;
	prTitle: string;
	/** Raw unified diff content */
	diff: string;
}

/** HTML preview tab (renders HTML in a sandboxed iframe) */
export interface HtmlPreviewTab extends BaseTab {
	type: "html-preview";
	title: string;
	repoPath: string;
	filePath: string;
	fileName: string;
	fsRoot?: string;
}

/** Native Command Overview panel tab */
export interface CommandOverviewTab extends BaseTab {
	type: "command-overview";
	title: string;
}

/** Discriminated union of all markdown tab types */
export type MdTabData =
	| FileTab
	| VirtualTab
	| PluginPanelTab
	| ClaudeUsageTab
	| GithubOpsTab
	| PrDiffTab
	| HtmlPreviewTab
	| CommandOverviewTab;

/**
 * Resolve a caller-supplied path (repo root or PTY cwd) to a registered repo path.
 *
 * Kept as a named forwarder because callers here only ever want the repo, not the
 * worktree branch. The matching itself lives in `utils/repoOwnership` — this used
 * to be its own longest-prefix loop that ignored worktrees, so a session inside a
 * linked worktree resolved to the wrong repo or to nothing at all.
 *
 * A function, not a `const` alias: an alias reads the repositories module the
 * instant this one is imported, so any test that stubs that module — even a test
 * that never touches a markdown tab — fails to load. Forwarding at call time
 * means only the callers that actually resolve a path need it.
 */
export function resolveRepoForCwd(path: string | null | undefined): string | null {
	return resolveRepoPathFor(path);
}

/**
 * Find an open file tab for the same file IN THE SAME REPO.
 *
 * `repoPath` is part of the identity on purpose. The old key was `fsRoot +
 * filePath`, and `fsRoot` collapses to `""` for every plugin-opened tab, so two
 * repos that both contain `README.md` (or a relative `plans/foo.md`) collided into
 * a single tab. Whichever repo asked second got handed the FIRST repo's tab, with
 * the first repo's content still in it.
 */
function findFileTab(
	tabs: Record<string, MdTabData>,
	repoPath: string,
	filePath: string,
	fsRoot?: string,
): FileTab | undefined {
	const effectiveRoot = fsRoot || repoPath;
	return Object.values(tabs).find(
		(tab): tab is FileTab =>
			tab.type === "file" &&
			tab.repoPath === repoPath &&
			(tab as FileTab).fsRoot === effectiveRoot &&
			tab.filePath === filePath,
	);
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

/** Imperative handles exposed by tab components (e.g. MarkdownTabHandle) */
const handles = new Map<string, unknown>();

/**
 * Notified whenever a plugin-panel tab leaves the store.
 *
 * The × button, middle-click, the tab context menu and closeTerminal all call
 * `remove` straight on the store — none of them can reach the plugin's
 * PanelHandle. Without this the owning plugin's message handler outlives its
 * panel, holding the plugin module alive for a tab that no longer exists.
 */
const pluginPanelClosedListeners = new Set<(tabId: string) => void>();

function createMdTabsStore() {
	const base = createTabManager<MdTabData>("markdown");

	/** Announce a plugin-panel closure to every subscriber. */
	function announceIfPluginPanel(tabId: string): void {
		if (base.get(tabId)?.type !== "plugin-panel") return;
		for (const listener of pluginPanelClosedListeners) listener(tabId);
	}

	return {
		state: base.state,

		/** Remove a tab. Plugin panels announce their own death on the way out. */
		remove(id: string): void {
			announceIfPluginPanel(id);
			base.remove(id);
		},

		setActive: base.setActive,

		clearAll(): void {
			for (const id of base.getIds()) announceIfPluginPanel(id);
			base.clearAll();
		},

		/** Subscribe to plugin-panel closures. Returns the unsubscribe function. */
		onPluginPanelClosed(listener: (tabId: string) => void): () => void {
			pluginPanelClosedListeners.add(listener);
			return () => {
				pluginPanelClosedListeners.delete(listener);
			};
		},
		get: base.get,
		getIds: base.getIds,
		getVisibleIds: base.getVisibleIds,
		getActive: base.getActive,
		getCount: base.getCount,
		setPinned: base.setPinned,
		reorderByIds: base.reorderByIds,

		/** Add a file-based markdown tab (or return existing if same file already open).
		 *  `fsRoot` overrides the filesystem root for I/O (e.g. worktree path). */
		add(repoPath: string, filePath: string, fsRoot?: string): string {
			const existing = findFileTab(base.state.tabs, repoPath, filePath, fsRoot);
			if (existing) {
				// Deliberately does NOT re-stamp repoPath/branchKey. It used to, which
				// meant reopening a file MOVED its tab into whichever repo had focus —
				// the tab, and the content in it, migrated away from its own repo.
				base.setActive(existing.id);
				return existing.id;
			}

			const id = base._nextId("md");
			const fileName = pathBasename(filePath) || filePath;
			const tab: FileTab = {
				type: "file",
				id,
				repoPath,
				filePath,
				fileName,
				branchKey: branchKeyFor(repoPath),
				fsRoot: fsRoot || repoPath,
			};
			const tabId = base._addTab(tab);

			return tabId;
		},

		/** Add a file-based markdown tab in the background (does not change activeId).
		 *  Returns tab ID, or null if a tab for the same file is already open. */
		addFileBackground(repoPath: string, filePath: string, fsRoot?: string): string | null {
			if (findFileTab(base.state.tabs, repoPath, filePath, fsRoot)) return null;

			const id = base._nextId("md");
			const fileName = pathBasename(filePath) || filePath;
			const tab: FileTab = {
				type: "file",
				id,
				repoPath,
				filePath,
				fileName,
				branchKey: branchKeyFor(repoPath),
				fsRoot: fsRoot || repoPath,
				pinned: true,
			};
			base._addTabBackground(tab);
			return id;
		},

		/** Add a virtual markdown tab (or return existing if same contentUri already open) */
		addVirtual(title: string, contentUri: string, repoPath?: string): string {
			const existing = Object.values(base.state.tabs).find(
				(tab) => tab.type === "virtual" && tab.contentUri === contentUri,
			) as VirtualTab | undefined;
			if (existing) {
				base.setActive(existing.id);

				return existing.id;
			}

			const id = base._nextId("md");
			const tab: VirtualTab = { type: "virtual", id, title, contentUri, pinned: true };
			if (repoPath) tab.repoPath = repoPath;
			const tabId = base._addTab(tab);

			return tabId;
		},

		/** Add a virtual markdown tab without making it active (background tab). Returns tab ID or null if already open. */
		addVirtualBackground(title: string, contentUri: string, repoPath?: string): string | null {
			const existing = Object.values(base.state.tabs).find(
				(tab) => tab.type === "virtual" && tab.contentUri === contentUri,
			) as VirtualTab | undefined;
			if (existing) return null; // already open — no-op

			const id = base._nextId("md");
			// Add to store without changing activeId
			const tab: VirtualTab = { type: "virtual", id, title, contentUri, pinned: true };
			if (repoPath) tab.repoPath = repoPath;
			base._addTabBackground(tab);
			return id;
		},

		/**
		 * Add a plugin panel tab, or reuse the one this plugin already opened under
		 * the same `panelKey`. Reuse refreshes html and title and activates the tab
		 * — the plugin asked for that panel, so the user must end up looking at it.
		 * Returns the tab ID.
		 */
		addPluginPanel(pluginId: string, panelKey: string, title: string, html: string): string {
			const existing = Object.values(base.state.tabs).find(
				(tab) =>
					tab.type === "plugin-panel" &&
					(tab as PluginPanelTab).pluginId === pluginId &&
					(tab as PluginPanelTab).panelKey === panelKey,
			) as PluginPanelTab | undefined;
			if (existing) {
				// Refresh html so plugin updates (e.g. after hot-reload or
				// re-open) replace stale content instead of silently keeping
				// the previous render.
				base._setState("tabs", existing.id, "html" as keyof MdTabData, html as MdTabData[keyof MdTabData]);
				base._setState("tabs", existing.id, "title" as keyof MdTabData, title as MdTabData[keyof MdTabData]);
				base.setActive(existing.id);
				return existing.id;
			}

			const id = base._nextId("md");
			// pinned: an SDK dashboard is global, not a per-repo view — it carries no
			// repoPath, so evictNonPinnedPluginPanelsForOtherRepos would leave it
			// alone either way. The flag is the honest label for a tab the user opened
			// deliberately and expects to find again, and it is what protects the
			// panel the day one of these does become repo-scoped.
			const tabId = base._addTab({
				type: "plugin-panel",
				id,
				title,
				pluginId,
				panelKey,
				html,
				pinned: true,
			} as PluginPanelTab);

			return tabId;
		},

		/**
		 * Open or update a UI tab (MCP-driven). Deduplicates on pluginId alone.
		 * focus=true (default): switch to this tab. focus=false: update content silently.
		 *
		 * originRepoPath: repo/cwd of the MCP caller. When resolvable to a
		 * registered repo, the tab is scoped there. When unresolvable, the tab
		 * is left unscoped (visible in all repos) rather than guessing from focus.
		 */
		openUiTab(
			pluginId: string,
			title: string,
			html: string,
			pinned: boolean,
			url?: string,
			focus = true,
			originRepoPath?: string,
		): string {
			const existing = Object.values(base.state.tabs).find(
				(tab) => tab.type === "plugin-panel" && (tab as PluginPanelTab).pluginId === pluginId,
			) as PluginPanelTab | undefined;
			if (existing) {
				base._setState("tabs", existing.id, "html" as keyof MdTabData, html as MdTabData[keyof MdTabData]);
				base._setState("tabs", existing.id, "title" as keyof MdTabData, title as MdTabData[keyof MdTabData]);
				if (url !== undefined)
					base._setState("tabs", existing.id, "url" as keyof MdTabData, url as MdTabData[keyof MdTabData]);
				if (focus) base.setActive(existing.id);
				return existing.id;
			}

			const id = base._nextId("md");
			// MCP `ui` tabs are design/preview surfaces: keep their own styling and
			// omit PLUGIN_BASE_CSS (#080). SDK plugin dashboards use addPluginPanel,
			// which leaves selfStyled unset so the base sheet is injected.
			const tab: PluginPanelTab = { type: "plugin-panel", id, title, pluginId, html, pinned, selfStyled: true };
			const resolvedRepo = resolveRepoForCwd(originRepoPath) ?? undefined;
			if (resolvedRepo) tab.repoPath = resolvedRepo;
			if (url) tab.url = url;
			if (focus) {
				return base._addTab(tab);
			}
			base._addTabBackground(tab);
			return id;
		},

		/** Remove a plugin-panel tab by its pluginId (the MCP 'id' param). No-op if not found. */
		closeUiTab(pluginId: string): void {
			const existing = Object.values(base.state.tabs).find(
				(tab) => tab.type === "plugin-panel" && (tab as PluginPanelTab).pluginId === pluginId,
			) as PluginPanelTab | undefined;
			if (existing) base.remove(existing.id);
		},

		/**
		 * Update the HTML content of an existing plugin panel tab.
		 *
		 * Returns false when the tab is gone — the user can close a panel from the
		 * tab bar at any time, and a plugin that keeps pushing renders into nothing
		 * has no other way to notice it should re-open.
		 */
		updatePluginPanel(tabId: string, html: string): boolean {
			const tab = base.get(tabId);
			if (tab?.type !== "plugin-panel") return false;
			base._setState("tabs", tabId, "html" as keyof MdTabData, html as MdTabData[keyof MdTabData]);
			return true;
		},

		/** Add the Claude Usage Dashboard tab (singleton — reuses existing if open) */
		addClaudeUsage(): string {
			const existing = Object.values(base.state.tabs).find((tab) => tab.type === "claude-usage") as
				| ClaudeUsageTab
				| undefined;
			if (existing) {
				base.setActive(existing.id);

				return existing.id;
			}

			const id = base._nextId("md");
			const tabId = base._addTab({ type: "claude-usage", id, title: "Claude Usage", pinned: true } as ClaudeUsageTab);

			return tabId;
		},

		/** Add the GitHub Ops Dashboard tab (singleton per repo — reuses existing if open) */
		addGithubOps(repoPath: string): string {
			const existing = Object.values(base.state.tabs).find(
				(tab) => tab.type === "github-ops" && (tab as GithubOpsTab).repoPath === repoPath,
			) as GithubOpsTab | undefined;
			if (existing) {
				base.setActive(existing.id);

				return existing.id;
			}

			const id = base._nextId("md");
			const tabId = base._addTab({
				type: "github-ops",
				id,
				title: "GitHub Ops",
				repoPath,
				pinned: true,
			} as GithubOpsTab);

			return tabId;
		},

		/** Add the Command Overview panel tab (singleton — reuses existing if open) */
		addCommandOverview(): string {
			const existing = Object.values(base.state.tabs).find((tab) => tab.type === "command-overview") as
				| CommandOverviewTab
				| undefined;
			if (existing) {
				base.setActive(existing.id);
				return existing.id;
			}

			const id = base._nextId("md");
			return base._addTab({ type: "command-overview", id, title: "Commands", pinned: true } as CommandOverviewTab);
		},

		/** Add a PR diff tab (or reuse existing for same repo+prNumber, updating diff content) */
		addPrDiff(repoPath: string, prNumber: number, prTitle: string, diff: string): string {
			const existing = Object.values(base.state.tabs).find(
				(tab) =>
					tab.type === "pr-diff" &&
					(tab as PrDiffTab).repoPath === repoPath &&
					(tab as PrDiffTab).prNumber === prNumber,
			) as PrDiffTab | undefined;
			if (existing) {
				// Update diff content in case it changed
				base._setState("tabs", existing.id, "diff" as keyof MdTabData, diff as MdTabData[keyof MdTabData]);
				base.setActive(existing.id);
				return existing.id;
			}

			const id = base._nextId("md");
			const title = `PR #${prNumber}`;
			const tabId = base._addTab({
				type: "pr-diff",
				id,
				title,
				repoPath,
				prNumber,
				prTitle,
				diff,
				pinned: false,
			} as PrDiffTab);
			return tabId;
		},

		/** Add an HTML preview tab (or return existing if same file already open) */
		addHtmlPreview(repoPath: string, filePath: string, fsRoot?: string): string {
			const effectiveRoot = fsRoot || repoPath;
			// Same identity rule as findFileTab: the repo is part of what makes this
			// preview "the same preview". Without it a preview opened from one repo is
			// handed back to another, which is how a preview full of one project's
			// output turned up in a project that had nothing to do with it.
			const existing = Object.values(base.state.tabs).find(
				(tab) =>
					tab.type === "html-preview" &&
					tab.repoPath === repoPath &&
					(tab as HtmlPreviewTab).fsRoot === effectiveRoot &&
					tab.filePath === filePath,
			) as HtmlPreviewTab | undefined;
			if (existing) {
				base.setActive(existing.id);
				return existing.id;
			}

			const id = base._nextId("md");
			const fileName = pathBasename(filePath) || filePath;
			const tab: HtmlPreviewTab = {
				type: "html-preview",
				id,
				title: fileName,
				repoPath,
				filePath,
				fileName,
				branchKey: branchKeyFor(repoPath),
				fsRoot: effectiveRoot,
			};
			return base._addTab(tab);
		},

		/** Set a tab's font size (clamped to [MIN, MAX]). */
		setFontSize(id: string, fontSize: number): void {
			if (!base.state.tabs[id]) return;
			const clamped = Math.max(MD_MIN_FONT_SIZE, Math.min(MD_MAX_FONT_SIZE, fontSize));
			base._setState("tabs", id, "fontSize" as keyof MdTabData, clamped as MdTabData[keyof MdTabData]);
		},

		/** Get a tab's effective font size (falls back to default). */
		getFontSize(id: string): number {
			return base.state.tabs[id]?.fontSize ?? MD_DEFAULT_FONT_SIZE;
		},

		/** Zoom in the active markdown tab by one step. */
		zoomIn(): void {
			const id = base.state.activeId;
			if (!id) return;
			this.setFontSize(id, (base.state.tabs[id]?.fontSize ?? MD_DEFAULT_FONT_SIZE) + MD_FONT_STEP);
		},

		/** Zoom out the active markdown tab by one step. */
		zoomOut(): void {
			const id = base.state.activeId;
			if (!id) return;
			this.setFontSize(id, (base.state.tabs[id]?.fontSize ?? MD_DEFAULT_FONT_SIZE) - MD_FONT_STEP);
		},

		/** Reset the active markdown tab to the default font size. */
		zoomReset(): void {
			const id = base.state.activeId;
			if (!id) return;
			this.setFontSize(id, MD_DEFAULT_FONT_SIZE);
		},

		/** Register an imperative handle for a tab (e.g. MarkdownTabHandle with openSearch) */
		setHandle(tabId: string, handle: unknown): void {
			handles.set(tabId, handle);
		},

		/** Remove the imperative handle when a tab component unmounts */
		clearHandle(tabId: string): void {
			handles.delete(tabId);
		},

		/** Retrieve the imperative handle for a tab */
		getHandle<T = unknown>(tabId: string): T | undefined {
			return handles.get(tabId) as T | undefined;
		},

		/**
		 * Evict non-pinned plugin-panel tabs whose repoPath is set and doesn't match
		 * the given repo. Without this, every visited repo leaves a stale UI tab in
		 * state.tabs forever — invisible (getVisibleIds hides them) but still holding
		 * HTML in memory. Called on repo switch. Pinned tabs and tabs with no
		 * repoPath (globally scoped) are preserved. Non-plugin-panel tabs (file,
		 * virtual, pr-diff, html-preview, etc.) are untouched — they have their own
		 * lifecycle and users rely on them persisting across repo switches.
		 */
		evictNonPinnedPluginPanelsForOtherRepos(currentRepoPath: string | null): void {
			base._clearWhere(
				(tab) => tab.type === "plugin-panel" && !tab.pinned && !!tab.repoPath && tab.repoPath !== currentRepoPath,
			);
		},

		/** Clear all file-based markdown tabs for a repository (virtual tabs are unaffected) */
		clearForRepo(repoPath: string): void {
			base._clearWhere((tab) => tab.type === "file" && (tab as FileTab).repoPath === repoPath);
		},

		/** Get file-based tabs for a specific repository */
		getForRepo(repoPath: string): FileTab[] {
			return Object.values(base.state.tabs).filter(
				(tab): tab is FileTab => tab.type === "file" && tab.repoPath === repoPath,
			);
		},
	};
}

export const mdTabsStore = createMdTabsStore();
